# ğŸ“¦ App-Informationen & ğŸŒ Profil
spring:
  application:
    name: tasks
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    default: local-dev
    #active: dev  # Optionen: dev, test oder prod

# ğŸ§¾ Versioning
application:
  version: 1.0.0

# ğŸ“‹ Logging-Konfiguration
logging:
  interceptor:
    enabled: console  # MÃ¶gliche Werte: json oder console
