name: CI Dev Compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dev-compose:
    runs-on: ubuntu-latest

    env:
      POSTGRES_USER: admin
      POSTGRES_DB: tasks_dev_db
      POSTGRES_PASSWORD: adminpass
      APP_DB_USER: dev_user
      APP_DB_PASSWORD: dev_secret
      DB_NAME: tasks_dev_db
      DB_HOST: db
      SPRING_PROFILES_ACTIVE: compose-dev
      DB_PORT: 5432
      APP_PORT: 8080

    steps:
      - name: ğŸ“¥ Checkout Code
        uses: actions/checkout@v3

      - name: ğŸ³ Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: ğŸ§ª Starte Compose Umgebung
        run: make -f Makefile.compose-ci ci-dev-up # run: docker compose -f docker-compose-dev-ci.yml up -d

      - name: ğŸ” Zeige Logs
        run: docker compose -f docker-compose-dev-ci.yml logs

      - name: ğŸ§ª Healthcheck
        run: make -f Makefile.compose-ci ci-dev-healthcheck-retry

      #- name: ğŸ“‹ Tasklist-Check
      #  run: make -f Makefile.compose-ci ci-dev-tasklist-check

      - name: ğŸŒ Versuche Verbindung zu App...
        run: make -f Makefile.compose-ci ci-dev-debug

      - name: ğŸ§¹ Stoppe Umgebung
        run: make -f Makefile.compose-ci ci-dev-down # run: docker compose -f docker-compose-dev-ci.yml down
